// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3lPCVYEKje85sBvMmigM7xtX-RhxAows',
    appId: '1:481196523769:web:4fcb9a902fb18002cca228',
    messagingSenderId: '481196523769',
    projectId: 'poemgenerator-a2d7a',
    authDomain: 'poemgenerator-a2d7a.firebaseapp.com',
    storageBucket: 'poemgenerator-a2d7a.appspot.com',
    measurementId: 'G-QC8HRTX7MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAmRQRheun0P903ziMo2SGyW6_totwoz4',
    appId: '1:481196523769:android:52893f5719dd34fbcca228',
    messagingSenderId: '481196523769',
    projectId: 'poemgenerator-a2d7a',
    storageBucket: 'poemgenerator-a2d7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtjVj8X3F2qwUCCcTELw4WC1DlzPZbZmQ',
    appId: '1:481196523769:ios:314bc5b8f83c935ecca228',
    messagingSenderId: '481196523769',
    projectId: 'poemgenerator-a2d7a',
    storageBucket: 'poemgenerator-a2d7a.appspot.com',
    iosBundleId: 'com.example.poemGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtjVj8X3F2qwUCCcTELw4WC1DlzPZbZmQ',
    appId: '1:481196523769:ios:314bc5b8f83c935ecca228',
    messagingSenderId: '481196523769',
    projectId: 'poemgenerator-a2d7a',
    storageBucket: 'poemgenerator-a2d7a.appspot.com',
    iosBundleId: 'com.example.poemGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3lPCVYEKje85sBvMmigM7xtX-RhxAows',
    appId: '1:481196523769:web:c3de1fe8d15034cbcca228',
    messagingSenderId: '481196523769',
    projectId: 'poemgenerator-a2d7a',
    authDomain: 'poemgenerator-a2d7a.firebaseapp.com',
    storageBucket: 'poemgenerator-a2d7a.appspot.com',
    measurementId: 'G-46PYDVNLVP',
  );
}
